spring:
  application:
    name: shushu-upload
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      authentication-database: admin
upload-config-path: classpath:config-demo.json
server-list-file: classpath:serverlist
