spring:
  application:
    name: shushu-upload
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      authentication-database: upload
      database: upload
xa:
  config:
    config-path: classpath:config-demo.json
    server-list-file: classpath:serverlist
    startDay: 2019-11-14
    pushType: FILE
    logSource:
      rootDirs: E:/ziyu
      logDir: 14-20
      intervalSecond: 300
    eventPush:
      serverUrl:
      appId:


