xa:
  config:
    config-path: classpath:config.json
    server-list-file: classpath:serverlist
    startDay: 2019-11-14
    pushType:
      console: true
      fileDebug: false
      file: false
      http: false
    logSource:
      rootDirs: /Users/weiwei/Documents/program/program-data
      logDir: 14-20
      intervalSecond: 300
    database:
      user-name: root
      password: root
      nameprefix: mhyx_
    eventPush:
      serverUrl:
      appId:
spring:
  application:
    name: shushu-upload
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost/upload?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      pool-name: user-1
      minimum-idle: 30
      maximum-pool-size: 30
      connectionTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      register-mbeans: true
